name: Weekly Pull Request Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # This will run the workflow every Sunday at midnight UTC

permissions:
  issues: write
  pull-requests: read

jobs:
  build:
    name: pull request metrics
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: 'matos61/Pull_Request_testing'
        ref: main
        token: ${{ secrets.METRIC_TOKEN }}

    - name: List files
      run: |
        ls -al

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install @octokit/graphql node-fetch

    - name: Fetch pull requests
      env:
        GITHUB_TOKEN: ${{ secrets.METRIC_TOKEN }}
      run: |
        echo "Fetching pull requests"
        node fetch_prs.mjs
        cat prs.json  # Output the content of prs.json to the log for debugging

    - name: Generate pull request metrics
      run: |
        echo "Generating metrics report"
        python generate_pr_metrics.py

    - name: Create issue
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: Weekly Pull Request Metrics Report
        token: ${{ secrets.METRIC_TOKEN }}
        content-filepath: ./pull_request_metrics.md
        assignees: matos61
