name: Monthly Pull Request Metrics
on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 1 * *'

permissions:
  issues: write
  pull-requests: read

jobs:
  build:
    name: pull request metrics
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: 'matos61/Pull_Request_testing'
        ref: main

    - name: List files
      run: |
        ls -al

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install @octokit/graphql node-fetch

    - name: Get dates for last month
      id: get_dates
      shell: bash
      run: |
        first_day=$(date -d "last month" +%Y-%m-01)
        last_day=$(date -d "$first_day +1 month -1 day" +%Y-%m-%d)
        echo "first_day=$first_day" >> "$GITHUB_ENV"
        echo "last_day=$last_day" >> "$GITHUB_ENV"
        echo "last_month=$first_day..$last_day" >> "$GITHUB_ENV"

    - name: Debug date range
      run: echo ${{ env.last_month }}

    - name: Fetch pull requests
      env:
        GITHUB_TOKEN: ${{ secrets.METRIC_TOKEN }}
      run: |
        echo "Fetching pull requests"
        node fetch_prs.mjs

    - name: Generate pull request metrics
      run: |
        echo "Generating metrics report"
        python generate_pr_metrics.py 'prs.json'

    - name: Create issue
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: Monthly Pull Request Metrics Report
        token: ${{ secrets.METRIC_TOKEN }}
        content-filepath: ./pull_request_metrics.md
        assignees: matos61
